language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true

  allow_failures:
    - php: 7
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update -n
  - if [[ $TRAVIS_PULL_REQUEST = false ]]; then composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN; fi
  - if [[ $TRAVIS_PHP_VERSION = hhvm || $TRAVIS_PHP_VERSION = 7 ]]; then sed -i '/ext-xdebug/d' composer.json; fi
  - pushd "${HOME}"
  - curl -L "http://cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz" | gunzip -c | tar x
  - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
  - popd
  - cmake --version
  - npm install -g npm@next
  - npm --version
  - npm install -g gulp
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"


install:
  - travis_retry composer install -n --prefer-dist

script:
  - gulp
  - mkdir _build && cd _build
  - cmake ..
  - ctest -V
