version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: MySQL Build
          command: |
            set -x
            rm ./docker-compose.yml
            cp ./.circleci/docker-compose-mysql-build.yml ./docker-compose.yml
            docker-compose build --build-arg DEVELOPMENT_BUILD=1 cdash
      - run:
          name: Spin Up MySQL Build
          command: |
            set -x
            docker-compose up -d
            bash -c "docker/bash/circleci-wait.bash http://localhost/ping 12"
      - run:
          name: Test MySQL Build
          command: docker exec --user www-data cdash bash -c "/usr/bin/ctest -VV"
      - run:
          name: Save Test Artifacts
          command: docker cp cdash:/home/kitware/cdash/storage/logs/laravel-$(date +%F).log /tmp/cdash-mysql-build.log
      - store_artifacts:
          path: /tmp/cdash-mysql-build.log
          destination: cdash-mysql-build.log
      - run:
          name: Tear Down MySQL Build
          command: docker-compose down
      - run:
          name: Spin Up Postgres Build
          command: |
            set -x
            rm ./docker-compose.yml
            cp ./.circleci/docker-compose-postgres-build.yml ./docker-compose.yml
            docker-compose up -d
      - run:
          name: Configure Postgress Build
          command: |
            set -x
            docker exec -it cdash bash -c "/usr/bin/cmake -DCDASH_DB_HOST=postgres -DCDASH_DB_TYPE=pgsql -DCDASH_DB_LOGIN=postgres -DCDASH_DB_PASS=cdash4simpletest .."
            docker exec -it postgres_cdash bash -c "/usr/bin/createdb -U postgres --no-password cdash4simpletest"
      - run:
          name: Test Postgres Build
          command: docker exec --user www-data cdash bash -c "/usr/bin/ctest -VV"
