version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: |
            set -x
            docker-compose build --build-arg DEVELOPMENT_BUILD=1 cdash
      - run:
          name: Verify Build
          command: |
            set -x
            docker-compose up -d
            bash -c "docker/bash/circleci-wait.bash http://localhost/ping 12"
      - run:
          name: Test
          command: docker exec cdash bash -c "/usr/bin/ctest -VV"
