version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: MySQL Build
          command: |
            set -x
            rm ./docker-compose.yml
            cp ./.circleci/docker-compose-mysql-build.yml ./docker-compose.yml
            docker-compose build --build-arg DEVELOPMENT_BUILD=1 cdash
      - run:
          name: Verify Build
          command: |
            set -x
            docker-compose up -d
            bash -c "docker/bash/circleci-wait.bash http://localhost/ping 12"
      - run:
          name: Test
          command: docker exec --user www-data cdash bash -c "/usr/bin/ctest -VV"
