- name: base packages
  sudo: yes
  apt:
    name={{ item }}
    state=present
  with_items:
    - build-essential
    - cmake
    - git

- name: ensure docroot exists
  sudo: yes
  file:
    path=/var/www/CDash
    state=directory
    owner=vagrant
    group=vagrant

- name: add apache user to the vagrant group
  sudo: yes
  user:
    name=www-data
    groups=vagrant
    append=yes

- name: clone cdash
  git:
    repo=https://github.com/Kitware/CDash.git
    version=master
    dest=/var/www/CDash

- name: install php dependencies
  command: "composer install"
  args:
    chdir: /var/www/CDash

- name: install npm dependencies
  shell: "source /home/vagrant/.profile && npm install"
  args:
    chdir: /var/www/CDash
    executable: /bin/bash

- name: run gulp
  shell: "source /home/vagrant/.profile && ./node_modules/.bin/gulp"
  args:
    chdir: /var/www/CDash
    executable: /bin/bash
